dist: trusty
language: java

jdk:
    - oraclejdk8
    - openjdk8


before_install:
    - echo `echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"`

install:
    - mvn install -Djava.version=`echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"` -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn package -Djava.version=`echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"`
